### ISSUE TITLE
Security Concern

### ISSUE THREAD

**Issue by ZumiYumi** [goby-lang/sample-web-app#46]
Hello, I am a security researcher and I would like to disclose a potential vulnerability within this application. Is there an email or emails I could contact the developers with my finding and suggested remediation to finding?

**Comment by st0012** [comment]
Hi, please email to stan001212@gmail.com
But at the same time, this app is not in used anymore.

**Comment by ZumiYumi** [comment]
Hello I sent an email with the security concern, thank you.
Closing this ticket.
